# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(upload_to='media/'),
        ),
    ]
