# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20180228_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
