# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20180228_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(upload_to='documents/', verbose_name='Фоточка'),
        ),
    ]
