# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(default=' ', upload_to='documents/', verbose_name='Фоточка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default=' ', max_length=100, verbose_name='Url'),
        ),
    ]
