# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_auto_20181207_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=555, verbose_name='Цитата')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('img', models.FileField(upload_to='documents/', verbose_name='Аватарка')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
