# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-03 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
