# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_post_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Фоточка'),
        ),
    ]
